"""与实盘后端硬隔离的持久化模拟交易环境。"""

from finboard_simulation.contracts import (
    SIMULATION_MODE,
    SIMULATION_SCHEMA_VERSION,
    SimulationAccountStatus,
    SimulationBarEvent,
    SimulationConfig,
    SimulationConflictError,
    SimulationDecision,
    SimulationError,
    SimulationIsolationError,
    SimulationMarketEventStatus,
    SimulationMatchingConfig,
    SimulationNotFoundError,
    SimulationPositionEffect,
    SimulationProcessResult,
    SimulationPromotionStatus,
    SimulationRiskError,
    SimulationRiskLimits,
    SimulationSessionStatus,
    SimulationSourceMode,
    SimulationTarget,
    SimulationTransitionError,
    new_simulation_id,
    stable_checksum,
)
from finboard_simulation.matching import (
    MatchAction,
    MatchOutcome,
    PendingOrder,
    match_order,
)
from finboard_simulation.repository import SimulationRepository
from finboard_simulation.rules import (
    SimulationAssetRule,
    resolve_simulation_rule,
    simulation_rule_keys,
)
from finboard_simulation.service import SimulationService, bar_from_payload

__all__ = [
    "SIMULATION_MODE",
    "SIMULATION_SCHEMA_VERSION",
    "MatchAction",
    "MatchOutcome",
    "PendingOrder",
    "SimulationAccountStatus",
    "SimulationAssetRule",
    "SimulationBarEvent",
    "SimulationConfig",
    "SimulationConflictError",
    "SimulationDecision",
    "SimulationError",
    "SimulationIsolationError",
    "SimulationMarketEventStatus",
    "SimulationMatchingConfig",
    "SimulationNotFoundError",
    "SimulationPositionEffect",
    "SimulationProcessResult",
    "SimulationPromotionStatus",
    "SimulationRepository",
    "SimulationRiskError",
    "SimulationRiskLimits",
    "SimulationService",
    "SimulationSessionStatus",
    "SimulationSourceMode",
    "SimulationTarget",
    "SimulationTransitionError",
    "bar_from_payload",
    "match_order",
    "new_simulation_id",
    "resolve_simulation_rule",
    "simulation_rule_keys",
    "stable_checksum",
]
