"""factor_snapshots_and_selection_versions

Revision ID: 560f1271f3f6
Revises: 9fc4abf81320
Create Date: 2026-07-27 05:02:01.815652

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "560f1271f3f6"
down_revision = "9fc4abf81320"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "factor_snapshots",
        sa.Column("decision_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("dataset_versions", sa.JSON(), nullable=False),
        sa.Column("factor_version", sa.String(length=32), nullable=False),
        sa.Column("static_universe", sa.JSON(), nullable=False),
        sa.Column("selected_symbols", sa.JSON(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("skip_reason", sa.Text(), nullable=True),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_factor_snapshot_decision_effective",
        "factor_snapshots",
        ["decision_at", "effective_date"],
        unique=False,
    )
    op.create_index(
        "ix_factor_snapshot_effective_decision",
        "factor_snapshots",
        ["effective_date", "decision_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_factor_snapshots_checksum"), "factor_snapshots", ["checksum"], unique=True
    )
    op.create_index(
        op.f("ix_factor_snapshots_decision_at"), "factor_snapshots", ["decision_at"], unique=False
    )
    op.create_index(
        op.f("ix_factor_snapshots_effective_date"),
        "factor_snapshots",
        ["effective_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_factor_snapshots_source"), "factor_snapshots", ["source"], unique=False
    )
    op.create_index(
        op.f("ix_factor_snapshots_status"), "factor_snapshots", ["status"], unique=False
    )
    op.create_table(
        "factor_values",
        sa.Column("snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("factor_name", sa.String(length=64), nullable=False),
        sa.Column("factor_version", sa.String(length=32), nullable=False),
        sa.Column(
            "value", sa.Numeric(precision=28, scale=8, decimal_return_scale=8), nullable=False
        ),
        sa.Column("global_rank", sa.Integer(), nullable=True),
        sa.Column("industry_rank", sa.Integer(), nullable=True),
        sa.Column("industry_code", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["snapshot_id"], ["factor_snapshots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "snapshot_id", "symbol", "factor_name", name="uq_factor_value_snapshot_symbol_factor"
        ),
    )
    op.create_index(
        "ix_factor_value_factor_symbol", "factor_values", ["factor_name", "symbol"], unique=False
    )
    op.create_index(
        "ix_factor_value_symbol_factor", "factor_values", ["symbol", "factor_name"], unique=False
    )
    op.create_index(
        op.f("ix_factor_values_snapshot_id"), "factor_values", ["snapshot_id"], unique=False
    )
    op.add_column(
        "backtest_runs",
        sa.Column(
            "selection",
            sa.JSON(),
            server_default=sa.text("'{}'::json"),
            nullable=False,
        ),
    )
    op.add_column(
        "backtest_runs",
        sa.Column(
            "dataset_versions",
            sa.JSON(),
            server_default=sa.text("'{}'::json"),
            nullable=False,
        ),
    )
    op.add_column("backtest_runs", sa.Column("factor_version", sa.String(length=32), nullable=True))
    op.add_column(
        "backtest_runs",
        sa.Column(
            "selection_snapshots",
            sa.JSON(),
            server_default=sa.text("'[]'::json"),
            nullable=False,
        ),
    )
    op.add_column(
        "strategy_presets",
        sa.Column(
            "selection",
            sa.JSON(),
            server_default=sa.text("'{}'::json"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("strategy_presets", "selection")
    op.drop_column("backtest_runs", "selection_snapshots")
    op.drop_column("backtest_runs", "factor_version")
    op.drop_column("backtest_runs", "dataset_versions")
    op.drop_column("backtest_runs", "selection")
    op.drop_index(op.f("ix_factor_values_snapshot_id"), table_name="factor_values")
    op.drop_index("ix_factor_value_symbol_factor", table_name="factor_values")
    op.drop_index("ix_factor_value_factor_symbol", table_name="factor_values")
    op.drop_table("factor_values")
    op.drop_index(op.f("ix_factor_snapshots_status"), table_name="factor_snapshots")
    op.drop_index(op.f("ix_factor_snapshots_source"), table_name="factor_snapshots")
    op.drop_index(op.f("ix_factor_snapshots_effective_date"), table_name="factor_snapshots")
    op.drop_index(op.f("ix_factor_snapshots_decision_at"), table_name="factor_snapshots")
    op.drop_index(op.f("ix_factor_snapshots_checksum"), table_name="factor_snapshots")
    op.drop_index("ix_factor_snapshot_effective_decision", table_name="factor_snapshots")
    op.drop_index("ix_factor_snapshot_decision_effective", table_name="factor_snapshots")
    op.drop_table("factor_snapshots")
    # ### end Alembic commands ###
