"""finboard-data: 历史行情与时点化研究数据源抽象及实现。

akshare / yfinance / tushare / pyarrow 均为 lazy import,Linux CI 环境无需安装。
"""

from finboard_data.akshare_provider import AkShareProvider
from finboard_data.assets import (
    ContinuousFuturesBuildError,
    CoverageEntry,
    CoverageReport,
    InstrumentMetadataProvider,
    InstrumentMetadataProviderError,
    InstrumentRegistry,
    InstrumentResolutionError,
    audit_dataset_coverage,
    build_continuous_series,
    resolve_market_by_code,
)
from finboard_data.base import HistoricalDataProvider
from finboard_data.factors import (
    FACTOR_CATALOG,
    FACTOR_VERSION,
    FactorDefinition,
    FactorFrequency,
    FactorInputBatch,
    FactorInputRecord,
    FactorName,
    FactorResearchReader,
    FactorSelectionConfig,
    FactorSnapshot,
    FactorSnapshotStatus,
    FactorSnapshotWriter,
    FactorUnit,
    FactorValue,
    PointInTimeSafety,
    RankingScope,
    factor_catalog,
)
from finboard_data.quality import (
    QualityIssue,
    QualityReport,
    QualitySeverity,
    QualityStatus,
    ResearchDataQualityValidator,
)
from finboard_data.research import (
    DailySecurityMetrics,
    FinancialIndicator,
    IndustryMembership,
    InstrumentProfile,
    ResearchDataConfigurationError,
    ResearchDataContractError,
    ResearchDataDependencyError,
    ResearchDataError,
    ResearchDataProvider,
    ResearchDataUpstreamError,
)
from finboard_data.symbols import (
    SymbolEntry,
    SymbolPoolConfig,
    load_symbol_pool,
    save_symbol_pool,
)
from finboard_data.tushare_provider import TushareResearchDataProvider
from finboard_data.yfinance_provider import YFinanceProvider

__all__ = [
    "FACTOR_CATALOG",
    "FACTOR_VERSION",
    "AkShareProvider",
    "ContinuousFuturesBuildError",
    "CoverageEntry",
    "CoverageReport",
    "DailySecurityMetrics",
    "FactorDefinition",
    "FactorFrequency",
    "FactorInputBatch",
    "FactorInputRecord",
    "FactorName",
    "FactorResearchReader",
    "FactorSelectionConfig",
    "FactorSnapshot",
    "FactorSnapshotStatus",
    "FactorSnapshotWriter",
    "FactorUnit",
    "FactorValue",
    "FinancialIndicator",
    "HistoricalDataProvider",
    "IndustryMembership",
    "InstrumentMetadataProvider",
    "InstrumentMetadataProviderError",
    "InstrumentProfile",
    "InstrumentRegistry",
    "InstrumentResolutionError",
    "PointInTimeSafety",
    "QualityIssue",
    "QualityReport",
    "QualitySeverity",
    "QualityStatus",
    "RankingScope",
    "ResearchDataConfigurationError",
    "ResearchDataContractError",
    "ResearchDataDependencyError",
    "ResearchDataError",
    "ResearchDataProvider",
    "ResearchDataQualityValidator",
    "ResearchDataUpstreamError",
    "SymbolEntry",
    "SymbolPoolConfig",
    "TushareResearchDataProvider",
    "YFinanceProvider",
    "audit_dataset_coverage",
    "build_continuous_series",
    "factor_catalog",
    "load_symbol_pool",
    "resolve_market_by_code",
    "save_symbol_pool",
]
