"""AccessCredentialIssuer 单元测试(issue #118)。

验证:
* 凭证签发从 ProcessManager 读取 base_url + 密码;
* 授权校验:会话不存在 / 非 ACTIVE 拒绝;
* 脱敏视图密码替换为掩码。
"""

from __future__ import annotations

from datetime import UTC, datetime

import pytest

from finboard_opencode import (
    AccessCredentialIssuer,
    AccessNotAuthorizedError,
    OpenCodeAccessInfo,
    OpenCodeProcessConfig,
    OpenCodeProcessManager,
)
from finboard_opencode.schemas import ConversationRecord, ConversationStatus


@pytest.fixture
def manager() -> OpenCodeProcessManager:
    config = OpenCodeProcessConfig(
        port=4097, hostname="127.0.0.1", username="opencode", password="cfg-secret"
    )
    return OpenCodeProcessManager(config, manage_process=False)


@pytest.fixture
def issuer(manager) -> AccessCredentialIssuer:
    return AccessCredentialIssuer(manager, agent_name="finboard-researcher")


def _record(
    *,
    conversation_id: str = "CONV-20260101-aaaaaaaaaaaaaaaa",
    status: ConversationStatus = ConversationStatus.ACTIVE,
    session_id: str = "sess-1",
) -> ConversationRecord:
    now = datetime.now(UTC)
    return ConversationRecord(
        conversation_id=conversation_id,
        opencode_session_id=session_id,
        agent_run_id=None,
        title="t",
        status=status,
        agent_name="finboard-researcher",
        model_ref=None,
        last_event_seq=0,
        created_at=now,
        updated_at=now,
    )


def test_issue_returns_access_info(issuer) -> None:
    record = _record()
    info = issuer.issue(record, conversation_id=record.conversation_id)
    assert isinstance(info, OpenCodeAccessInfo)
    assert info.conversation_id == record.conversation_id
    assert info.opencode_session_id == "sess-1"
    assert info.web_url == "http://127.0.0.1:4097"
    assert info.username == "opencode"
    assert info.password == "cfg-secret"
    assert info.agent_name == "finboard-researcher"


def test_issue_rejects_missing_conversation(issuer) -> None:
    with pytest.raises(AccessNotAuthorizedError, match="conversation not found"):
        issuer.issue(None, conversation_id="CONV-missing")


@pytest.mark.parametrize(
    "status",
    [
        ConversationStatus.INTERRUPTED,
        ConversationStatus.COMPLETED,
        ConversationStatus.FAILED,
        ConversationStatus.ORPHANED,
    ],
)
def test_issue_rejects_non_active_status(issuer, status) -> None:
    record = _record(status=status)
    with pytest.raises(AccessNotAuthorizedError, match="status="):
        issuer.issue(record, conversation_id=record.conversation_id)


def test_issue_uses_autogenerated_password_when_config_empty() -> None:
    config = OpenCodeProcessConfig(password="")
    manager = OpenCodeProcessManager(config, manage_process=False)
    issuer = AccessCredentialIssuer(manager)
    info = issuer.issue(_record(), conversation_id="CONV-1")
    assert info.password
    assert info.password != ""


def test_redact_masks_password(issuer) -> None:
    info = issuer.issue(_record(), conversation_id="CONV-1")
    redacted = AccessCredentialIssuer.redact(info)
    assert redacted["password"] == "***"
    assert redacted["web_url"] == "http://127.0.0.1:4097"
    assert redacted["username"] == "opencode"
    assert redacted["conversation_id"] == info.conversation_id
