"""AccessCredentialIssuer 单元测试(issue #118 / 重构 #121)。

验证:
* 凭证签发从 ProcessManager 读取 base_url + 密码;
* 脱敏视图密码替换为掩码;
* issue_default 不依赖 conversation(#121 重构后唯一签发路径)。
"""

from __future__ import annotations

import pytest

from finboard_opencode import (
    AccessCredentialIssuer,
    OpenCodeAccessInfo,
    OpenCodeProcessConfig,
    OpenCodeProcessManager,
)


@pytest.fixture
def manager() -> OpenCodeProcessManager:
    config = OpenCodeProcessConfig(
        port=4097, hostname="127.0.0.1", username="opencode", password="cfg-secret"
    )
    return OpenCodeProcessManager(config, manage_process=False)


@pytest.fixture
def issuer(manager) -> AccessCredentialIssuer:
    return AccessCredentialIssuer(manager, agent_name="finboard-researcher")


def test_issue_default_returns_access_info(issuer) -> None:
    info = issuer.issue_default()
    assert isinstance(info, OpenCodeAccessInfo)
    assert info.web_url == "http://127.0.0.1:4097"
    assert info.username == "opencode"
    assert info.password == "cfg-secret"
    assert info.agent_name == "finboard-researcher"


def test_issue_default_uses_autogenerated_password_when_config_empty() -> None:
    config = OpenCodeProcessConfig(password="")
    manager = OpenCodeProcessManager(config, manage_process=False)
    issuer = AccessCredentialIssuer(manager)
    info = issuer.issue_default()
    assert info.password
    assert info.password != ""


def test_redact_masks_password(issuer) -> None:
    info = issuer.issue_default()
    redacted = AccessCredentialIssuer.redact(info)
    assert redacted["password"] == "***"
    assert redacted["web_url"] == "http://127.0.0.1:4097"
    assert redacted["username"] == "opencode"
    assert "conversation_id" not in redacted  # #121 重构后不再有 conversation 字段
